"""account module

Revision ID: 8fa987e5b6cb
Revises: 4eccd9482ee8
Create Date: 2026-10-01 11:47:27.555526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8fa987e5b6cb'
down_revision: Union[str, Sequence[str], None] = '4eccd9482ee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('phone_hash', sa.String(length=64), nullable=False, comment='HMAC-SHA256，查询与唯一约束用'),
    sa.Column('phone_cipher', sa.LargeBinary(), nullable=False, comment='AES-256-GCM，客服查看用'),
    sa.Column('phone_masked', sa.String(length=20), nullable=False, comment='138****8888，列表展示用'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Argon2id'),
    sa.Column('nickname', sa.String(length=64), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.SmallInteger(), server_default=sa.text('0'), nullable=False, comment='0未知 1男 2女'),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('member_level', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('member_expire', postgresql.TIMESTAMP(timezone=True, precision=3), nullable=True),
    sa.Column('credit_score', sa.Integer(), server_default=sa.text('700'), nullable=False, comment='信用分，售后风控用'),
    sa.Column('role', sa.String(length=16), server_default=sa.text("'buyer'"), nullable=False, comment='buyer/merchant/admin/finance'),
    sa.Column('status', sa.SmallInteger(), server_default=sa.text('1'), nullable=False, comment='1正常 2冻结 3注销'),
    sa.Column('failed_logins', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_until', postgresql.TIMESTAMP(timezone=True, precision=3), nullable=True, comment='锁定到期时间，见登录防爆破'),
    sa.Column('register_time', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('phone_hash', name='uk_user_phone_hash'),
    schema='account'
    )
    op.create_index('idx_user_role', 'user', ['role'], unique=False, schema='account')
    op.create_index('idx_user_status_time', 'user', ['status', 'register_time'], unique=False, schema='account')
    op.create_table('refresh_token',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='SHA-256(令牌原文)'),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True, precision=3), nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True, precision=3), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['account.user.id'], name=op.f('fk_refresh_token_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_token')),
    schema='account'
    )
    op.create_index('idx_refresh_token_expire', 'refresh_token', ['expires_at'], unique=False, schema='account', postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index('idx_refresh_token_user', 'refresh_token', ['user_id'], unique=False, schema='account')
    op.create_table('shop',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.SmallInteger(), server_default=sa.text('1'), nullable=False, comment='1正常 2关闭 3审核中'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['account.user.id'], name=op.f('fk_shop_owner_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop')),
    schema='account'
    )
    op.create_index('idx_shop_owner', 'shop', ['owner_user_id'], unique=False, schema='account')
    op.create_table('user_address',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('receiver_name', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='收货电话，展示时脱敏'),
    sa.Column('province', sa.String(length=32), nullable=False),
    sa.Column('city', sa.String(length=32), nullable=False),
    sa.Column('district', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.String(length=255), nullable=False),
    sa.Column('region_code', sa.String(length=16), nullable=False, comment='行政区划码，运费计算用'),
    sa.Column('tag', sa.String(length=16), nullable=True, comment='家/公司/学校'),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.SmallInteger(), server_default=sa.text('1'), nullable=False, comment='1有效 2已删除'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('status IN (1, 2)', name=op.f('ck_user_address_status_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['account.user.id'], name=op.f('fk_user_address_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_address')),
    schema='account'
    )
    op.create_index('idx_user_address_user', 'user_address', ['user_id', 'status'], unique=False, schema='account')
    op.create_index('uk_user_address_default', 'user_address', ['user_id'], unique=True, schema='account', postgresql_where=sa.text('is_default AND status = 1'))
    op.create_table('shop_member',
    sa.Column('shop_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('member_role', sa.String(length=16), server_default=sa.text("'owner'"), nullable=False, comment='owner/staff'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['account.shop.id'], name=op.f('fk_shop_member_shop_id')),
    sa.ForeignKeyConstraint(['user_id'], ['account.user.id'], name=op.f('fk_shop_member_user_id')),
    sa.PrimaryKeyConstraint('shop_id', 'user_id', name=op.f('pk_shop_member')),
    schema='account'
    )
    op.create_index('idx_shop_member_user', 'shop_member', ['user_id'], unique=False, schema='account')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_shop_member_user', table_name='shop_member', schema='account')
    op.drop_table('shop_member', schema='account')
    op.drop_index('uk_user_address_default', table_name='user_address', schema='account', postgresql_where=sa.text('is_default AND status = 1'))
    op.drop_index('idx_user_address_user', table_name='user_address', schema='account')
    op.drop_table('user_address', schema='account')
    op.drop_index('idx_shop_owner', table_name='shop', schema='account')
    op.drop_table('shop', schema='account')
    op.drop_index('idx_refresh_token_user', table_name='refresh_token', schema='account')
    op.drop_index('idx_refresh_token_expire', table_name='refresh_token', schema='account', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('refresh_token', schema='account')
    op.drop_index('idx_user_status_time', table_name='user', schema='account')
    op.drop_index('idx_user_role', table_name='user', schema='account')
    op.drop_table('user', schema='account')
    # ### end Alembic commands ###
