"""product module

Revision ID: b7dc4e986eee
Revises: 8fa987e5b6cb
Create Date: 2026-10-01 12:11:22.298780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7dc4e986eee'
down_revision: Union[str, Sequence[str], None] = '8fa987e5b6cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='NULL 表示一级类目'),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False, comment='1/2/3 级'),
    sa.Column('path', sa.String(length=128), nullable=False, comment='物化路径，形如 /1/10/101/'),
    sa.Column('sort', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.SmallInteger(), server_default=sa.text('1'), nullable=False, comment='1启用 2停用'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('level BETWEEN 1 AND 3', name=op.f('ck_category_level_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category')),
    sa.UniqueConstraint('parent_id', 'name', name='uk_category_parent_name'),
    schema='product'
    )
    op.create_index('idx_category_path', 'category', ['path'], unique=False, schema='product')
    op.create_index('idx_category_status_sort', 'category', ['status', 'sort'], unique=False, schema='product')
    op.create_table('spu',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('shop_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False, comment='末级类目 ID'),
    sa.Column('brand_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('sub_title', sa.String(length=255), nullable=True, comment='副标题/卖点'),
    sa.Column('main_image', sa.String(length=255), nullable=False, comment='主图，列表页用'),
    sa.Column('price_min', sa.BigInteger(), server_default=sa.text('0'), nullable=False, comment='展示最低价（分）'),
    sa.Column('price_max', sa.BigInteger(), server_default=sa.text('0'), nullable=False, comment='展示最高价（分）'),
    sa.Column('total_sold', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('review_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('review_score_sum', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('good_review_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('avg_score', sa.Numeric(precision=3, scale=2), server_default=sa.text('5.00'), nullable=False),
    sa.Column('status', sa.SmallInteger(), server_default=sa.text('1'), nullable=False, comment='1草稿 2上架 3下架 4违规下架 5待审核'),
    sa.Column('sort_weight', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('search_text', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('search_rank', sa.Numeric(precision=10, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='软删，物理删除会破坏订单语义'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('price_max >= price_min AND price_min >= 0', name=op.f('ck_spu_price_range_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spu')),
    schema='product'
    )
    op.create_index('idx_spu_category_status', 'spu', ['category_id', 'status'], unique=False, schema='product')
    op.create_index('idx_spu_on_shelf_category', 'spu', ['category_id', 'sort_weight'], unique=False, schema='product', postgresql_where=sa.text('status = 2 AND NOT deleted'))
    op.create_index('idx_spu_search_trgm', 'spu', ['search_text'], unique=False, schema='product', postgresql_using='gin', postgresql_ops={'search_text': 'gin_trgm_ops'})
    op.create_index('idx_spu_shop_status', 'spu', ['shop_id', 'status', 'created_at'], unique=False, schema='product')
    op.create_table('sku',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('spu_id', sa.BigInteger(), nullable=False),
    sa.Column('shop_id', sa.BigInteger(), nullable=False, comment='冗余，下单/拆单时免 join'),
    sa.Column('sku_code', sa.String(length=64), nullable=False, comment='商家编码'),
    sa.Column('spec_text', sa.String(length=255), nullable=False, comment='规格摘要，如"暗夜黑;256G"，写入订单快照'),
    sa.Column('price', sa.BigInteger(), nullable=False, comment='单价（分）'),
    sa.Column('cover_image', sa.String(length=255), nullable=False, comment='封面图，切换规格时展示'),
    sa.Column('weight_g', sa.Integer(), nullable=False, comment='物流重量（克），运费计算用'),
    sa.Column('status', sa.SmallInteger(), server_default=sa.text('1'), nullable=False, comment='1上架 2下架'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('price > 0', name=op.f('ck_sku_price_positive')),
    sa.CheckConstraint('weight_g > 0', name=op.f('ck_sku_weight_positive')),
    sa.ForeignKeyConstraint(['spu_id'], ['product.spu.id'], name=op.f('fk_sku_spu_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sku')),
    sa.UniqueConstraint('spu_id', 'sku_code', name='uk_sku_spu_code'),
    schema='product'
    )
    op.create_index('idx_sku_shop', 'sku', ['shop_id'], unique=False, schema='product')
    op.create_index('idx_sku_spu_status', 'sku', ['spu_id', 'status'], unique=False, schema='product')
    op.create_table('spec_group',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('spu_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('sort', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['spu_id'], ['product.spu.id'], name=op.f('fk_spec_group_spu_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spec_group')),
    sa.UniqueConstraint('spu_id', 'name', name='uk_spec_group_spu_name'),
    schema='product'
    )
    op.create_index('idx_spec_group_spu', 'spec_group', ['spu_id', 'sort'], unique=False, schema='product')
    op.create_table('spec_value',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('value', sa.String(length=32), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True, comment='色块图，前端渲染规格选择器'),
    sa.Column('sort', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['product.spec_group.id'], name=op.f('fk_spec_value_group_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spec_value')),
    sa.UniqueConstraint('group_id', 'value', name='uk_spec_value_group_value'),
    schema='product'
    )
    op.create_index('idx_spec_value_group', 'spec_value', ['group_id', 'sort'], unique=False, schema='product')
    op.create_table('sku_spec',
    sa.Column('sku_id', sa.BigInteger(), nullable=False),
    sa.Column('spec_group_id', sa.BigInteger(), nullable=False),
    sa.Column('spec_value_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['product.sku.id'], name=op.f('fk_sku_spec_sku_id')),
    sa.ForeignKeyConstraint(['spec_group_id'], ['product.spec_group.id'], name=op.f('fk_sku_spec_spec_group_id')),
    sa.ForeignKeyConstraint(['spec_value_id'], ['product.spec_value.id'], name=op.f('fk_sku_spec_spec_value_id')),
    sa.PrimaryKeyConstraint('sku_id', 'spec_group_id', name=op.f('pk_sku_spec')),
    schema='product'
    )
    op.create_index('idx_sku_spec_value', 'sku_spec', ['spec_value_id'], unique=False, schema='product')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sku_spec_value', table_name='sku_spec', schema='product')
    op.drop_table('sku_spec', schema='product')
    op.drop_index('idx_spec_value_group', table_name='spec_value', schema='product')
    op.drop_table('spec_value', schema='product')
    op.drop_index('idx_spec_group_spu', table_name='spec_group', schema='product')
    op.drop_table('spec_group', schema='product')
    op.drop_index('idx_sku_spu_status', table_name='sku', schema='product')
    op.drop_index('idx_sku_shop', table_name='sku', schema='product')
    op.drop_table('sku', schema='product')
    op.drop_index('idx_spu_shop_status', table_name='spu', schema='product')
    op.drop_index('idx_spu_search_trgm', table_name='spu', schema='product', postgresql_using='gin', postgresql_ops={'search_text': 'gin_trgm_ops'})
    op.drop_index('idx_spu_on_shelf_category', table_name='spu', schema='product', postgresql_where=sa.text('status = 2 AND NOT deleted'))
    op.drop_index('idx_spu_category_status', table_name='spu', schema='product')
    op.drop_table('spu', schema='product')
    op.drop_index('idx_category_status_sort', table_name='category', schema='product')
    op.drop_index('idx_category_path', table_name='category', schema='product')
    op.drop_table('category', schema='product')
    # ### end Alembic commands ###
